const images = [
    { src: 'images/kimbap.jpg', title: 'kimbap', description: 'Made some kimbap during quarantine!' },
    { src: 'images/spam_musubi.jpg', title: 'spam_musubi', description: 'Made some spam musubis during quarantine!' },
    { src: 'images/seaturtles.jpg', title: 'seaturtles', description: 'Some sea turtles I saw on a Hawaiian beach.' },
    { src: 'images/stickers.jpg', title: 'stickers', description: 'I like stickers a lot and these are some of my recent additions to my collection I got from campus fundraisers.' },
    { src: 'images/stickers2.jpg', title: 'stickers2', description: 'Stickers I got from Twitchcon! The Nezuko one is great' },
    { src: 'images/soap.jpg', title: 'soap', description: 'Carved this out of soap when I was bored.' },
    { src: 'images/soap2.jpg', title: 'soap2', description: 'Carved this out of soap when I was bored.' },
    { src: 'images/dontdead.jpg', title: 'dontdead', description: 'At universal studios!' },
    { src: 'images/viet_coffee.jpg', title: 'viet_coffee', description: 'Definitely not a coffee addict.' },
    { src: 'images/chicago_airport.jpg', title: 'chicago_airport', description: 'Chicago airport has this really cool underground bridge!' },
    { src: 'images/takoyaki.jpg', title: 'takoyaki', description: 'Delicious takoyaki :)' },
    { src: 'images/tattoo.jpg', title: 'tattoo', description: 'A \"tattoo\" my roomate drew on me' },
    { src: 'images/tattoo2.jpg', title: 'tattoo2', description: 'Another \"tattoo\" of a great meme.' },
    { src: 'images/tattoo3.jpg', title: 'tattoo3', description: 'Another \"tattoo\" of a great meme.' },
    { src: 'images/doggo.jpg', title: 'doggo', description: 'A dog at my workplace!' },
    { src: 'images/cat.jpg', title: 'cat', description: 'Cat cafe in Santa Barbara got those cute cats.' },
    { src: 'images/twitchcon.jpg', title: 'twitchcon', description: 'Took a picture with a random twich streamer... I thought she was lily pichu but she was one of her friends... still cool!' },
    { src: 'images/twitchcon2.jpg', title: 'twitchcon2', description: 'GAME OF KEYBOARDS' },
    { src: 'images/twitchcon3.jpg', title: 'twitchcon3', description: 'Another twitchcon picture!' },
    { src: 'images/turtle_collection.jpg', title: 'turtle_collection', description: 'I like collecting turtles in my free time, definitely not a problem...' },
    { src: 'images/portal_cube.jpg', title: 'portal_cube', description: 'I made this portal cube for my friend!' },
    { src: 'images/ditto.jpg', title: 'ditto', description: 'I like the ditto pokemon plushie series...' },
    { src: 'images/candle.jpg', title: 'candle', description: 'Made this candle in Santa Cruz!' },
    { src: 'images/kcon.jpg', title: 'kcon', description: 'Saw my queens MAMAMOO at Kcon 2019 <3' },
    { src: 'images/doggo2.jpg', title: 'doggo2', description: 'A doggo at work!' },
    { src: 'images/doggo3.jpg', title: 'doggo3', description: 'Another doggo at work!' },
    { src: 'images/mac.jpg', title: 'mac', description: 'A original Apple Mac someone brought into work!' },
    { src: 'images/banana_slug.jpg', title: 'banana_slug', description: 'Banana slugs!' },
    { src: 'images/squirtle.jpg', title: 'squirtle', description: 'Tried to make a squirtle from the squirtle squad with polymer clay LOL' },
    { src: 'images/turtles.jpg', title: 'turtles', description: 'Turtles at the UCSB pond!' },
    { src: 'images/avocados.jpg', title: 'avocados', description: 'I have these avocado plushies and I made the rightmost one out of felt to continue the chain :D' },
    { src: 'images/boba.jpg', title: 'boba', description: 'Cool boba flavors at a boba shop in LA!' },
    { src: 'images/tjturtle.jpg', title: 'tjturtle', description: 'Just a normal Sunday watching fishing videos with my turtle.' },
    { src: 'images/turtlepenguin.jpg', title: 'turtlepenguin', description: 'Some more felt creations I made.' }
  ];
  
  export default images;